### ISSUE TITLE
Relacionar tiempo semanal asignado con las estimaciones de las actividades.

### ISSUE THREAD

**Issue by namlin** [namlin/TareaProgramada2#11]
**En el foro aparece esto:
12. Como se relaciona el tiempo semanal asignado a los colaboradores con la estimación de tiempo de las tareas?

Tiempo semanal = 40 horas x colaborador => suma de tareas asignadas <= 40

Si una tarea ocupa 100 horas y solo hay una persona a tiempo completo, esta duraría 2,5 semanas

**Pero igual sigo sin entender...

**Comment by fallasandres** [comment]
1. Observación: Se había determinado al inicio, que se trabajará con actividades de una semana. Por lo tanto, deberíamos dejar fija la cantidad de horas (en 40, como el ejemplo)
2. Implementado: Por default, cuando generamos un colaborador, se le asignan 0 horas; cuando  se le asigna una actividad, a ese colaborador se le suma la cantidad de horas de la actividad.
3. Por implementar: Un método que verifique si al colaborador le quedan horas disponibles, caso contrario no se le pude asignar la actividad (suma de tareas asignadas <= 40)
