### ISSUE TITLE
Porcentages de asignación de los recursos de las actividades.

### ISSUE THREAD

**Issue by namlin** [namlin/TareaProgramada2#12]
**En el foro se emnciona esto:
3. En el punto 5 los recursos se les pone un % de asignación pero en el ejemplo usted puso cantidad (20 hojas blancas) cual manejamos, cantidad o %?

Usen %, si 20 hojas fuera el 100% del recurso requerido, si se asigna 5 hojas, estas corresponderían al 25% y así por el estilo

**Sigo sin entender cómo implementar esto y el por qué si los recursos perfectamente funcionan como un simple String.

**Comment by fallasandres** [comment]
Es muy ambiguo. En las indicaciones el se dan como ejemplo: 20 hojas, tijeras, goma; la única forma de colocarlo es un atributo tipo String, porque son diferentes materiales y cantidades. Para poder calcular un porcentaje, como en el ejemplo de las hojas del foro, el material si o si, debería darse en cantidades, pero tiene sentido; por ejemplo: 100% de una tijera. 
Sin embargo, se podría hacer una clase recurso, que tenga id, nombre, y una cantidad (20 hojas, 1 tijera, 1 goma) y que desde la actividad, se llame a ese objeto y se le descuente la cantidad de elementos que se requieran..
