### ISSUE TITLE
Implementar los impedimentos de una actividad.

### ISSUE THREAD

**Issue by namlin** [namlin/TareaProgramada2#13]
**Esto respondió el profe en la pregunta 14 del foro:
Tareas pueden hacerse acorde con la planificación o pueden tener impedimentos.
Impedimentos retrasarían o harían imposible la realización de una tarea.

-Me parece que éstos impedimentos pueden estar relaionados al proxy de las actividades.

**Comment by fallasandres** [comment]
Impedimentos: atributo de tipo string, en clase Actividad.
