### ISSUE TITLE
Agregar Documentación de las clases.

### ISSUE THREAD

**Issue by namlin** [namlin/TareaProgramada2#14]
Documentar todas las clases con javadoc.

**Comment by namlin** [comment]
Orden de clases:
Josué:
-Colaborador
-GestorListas
-Controlador

Andrés:
-Lista
-Recurso
-Actividad

Adrián:
-Visualizador
-Proxy

**Comment by fallasandres** [comment]
Hice colaborador y proxy a parte de las mías; no está de más revisarlas.
