### ISSUE TITLE
Ruta de las Actividades (Etapas).

### ISSUE THREAD

**Issue by namlin** [namlin/TareaProgramada2#7]
**Implementar las etapas en las actividades.

**En la pregunta 19 del foro se menciona:
19. ¿a qué se refiere con que el usuario define la composición y el nivel con que administra la lista?

El usuario define cuáles tareas {elementos, actividades} forman parte de la lista

Para entender el concepto de administración, pensemos en un tipo de lista que denominaremos etapas:

etapa1

tarea1

tarea5

etapa2

tarea 2

etapa3

tarea4

cada tarea (independiente de la etapa en que se encuentre) posee un nivel de completitud, al darse un 100% de completitud:

se pasa automáticamente de etapa i a etapa (i+1) : se asume secuencialida

el usuario define si quiere pasar esa tarea de epara i a etapa j

**Comment by fallasandres** [comment]
A partir de consulta al docente, se determina que la implementación actual, que permite que el usuario realice los cambios es válida, por lo tanto la completitud por porcentaje no se aplicará.
